name = "stock-checker"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cron job - her 30 dakikada bir çalışır
[triggers]
crons = ["*/30 * * * *"]  # Her 30 dakika

# Environment variables (bu değerleri daha sonra Cloudflare dashboard'dan ekleyeceğiz)
[vars]
# BOT_API = "7431981826:AAE3JlyFphcVFPCMHyqGXMYAvylIHF6NdZo"
# CHAT_ID = "503294787" 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true