name = "zara-stock-checker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Cron job - her 10 dakikada bir çalışır
[triggers]
crons = ["*/10 * * * *"]  # Her 10 dakika

# Environment variables (bu değerleri daha sonra Cloudflare dashboard'dan ekleyeceğiz)
[vars]
# BOT_API = "7431981826:AAE3JlyFphcVFPCMHyqGXMYAvylIHF6NdZo"
# CHAT_ID = "503294787" 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Secrets için wrangler secret put komutunu kullan:
# wrangler secret put BOT_API
# wrangler secret put CHAT_ID