name: ⚡ Super Fast Stock Checker

on:
  schedule:
    # Her 5 dakikada bir - GitHub Actions minimum limit
    - cron: '*/5 * * * *'
  
  # Manuel çalıştırma için
  workflow_dispatch:

  # Test için push event'i 
  push:
    branches: [ main ]
    paths: 
      - 'main_github.py'
      - 'scraperHelpers.py'
      - 'config.json'
      - '.github/workflows/*.yml'

jobs:
  super-fast-stock-check:
    runs-on: ubuntu-latest
    timeout-minutes: 4  # Maximum 4 dakika - hızlı execution
    
    steps:
    - name: ⚡ Checkout (sparse)
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          main_github.py
          scraperHelpers.py
          config.json
          requirements.txt
        sparse-checkout-cone-mode: false
      
    - name: ⚡ Python + Cache
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        
    - name: ⚡ Chrome (pre-installed)
      run: |
        google-chrome --version || sudo apt-get update && sudo apt-get install -y google-chrome-stable
        
    - name: ⚡ Install Dependencies (cached)
      run: |
        pip install -r requirements.txt
        
    - name: ⚡ Fast Stock Check
      run: |
        echo "⚡ Super Fast Check - $(date '+%H:%M:%S')"
        timeout 180 python main_github.py || echo "⚠️ Timeout or completed"
      env:
        BOT_API: ${{ secrets.BOT_API }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        PYTHONUNBUFFERED: 1
        CHROME_NO_SANDBOX: 1 