name: Zara Stock Checker

on:
  schedule:
    # Her 10 dakikada bir çalış (GitHub Actions minimum 5 dakika)
    - cron: '*/10 * * * *'
  
  # Manuel çalıştırma için
  workflow_dispatch:

  # Test için push event'i (sadece test amaçlı)
  push:
    branches: [ main ]
    paths: 
      - 'main_github.py'
      - 'scraperHelpers.py'
      - 'config.json'
      - '.github/workflows/*.yml'

jobs:
  stock-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Max 15 dakika çalışsın
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "BOT_API=${{ secrets.BOT_API }}" >> .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
        
    - name: Run stock checker
      run: |
        echo "🚀 Starting stock checker..."
        python main_github.py
      env:
        BOT_API: ${{ secrets.BOT_API }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        PYTHONUNBUFFERED: 1
        
    - name: Upload logs (if any errors)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          *.txt 